#ifndef CHARTGLOBAL_H
#define CHARTGLOBAL_H

#define QTCOMMERCIALCHART_VERSION_STR   "1.0"
#define QTCOMMERCIALCHART_VERSION 0x01

#if defined(QTCOMMERCIALCHART_LIBRARY)
#  define QTCOMMERCIALCHART_EXPORT Q_DECL_EXPORT
#else
#  define QTCOMMERCIALCHART_EXPORT Q_DECL_IMPORT
#endif

#define QTCOMMERCIALCHART_NAMESPACE QtCommercialChart

#ifdef QTCOMMERCIALCHART_NAMESPACE
# define QTCOMMERCIALCHART_BEGIN_NAMESPACE namespace QTCOMMERCIALCHART_NAMESPACE {
# define QTCOMMERCIALCHART_END_NAMESPACE }
# define QTCOMMERCIALCHART_USE_NAMESPACE using namespace QTCOMMERCIALCHART_NAMESPACE;
#else
# define QTCOMMERCIALCHART_BEGIN_NAMESPACE
# define QTCOMMERCIALCHART_END_NAMESPACE
# define QTCOMMERCIALCHART_USE_NAMESPACE
#endif

#endif
